### ISSUE TITLE
Support for Discord.js v12

### ISSUE THREAD

**Issue by Deph0** [dice-discord/commando-provider-keyv#23]
DiscordJS v12 introduces some breaking changes.

see https://discordjs.guide/additional-info/changes-in-v12.html

most noteworthy is the "cache", which means you need to add .cache on things you want to iterate over (e.g. [guilds.forEach](https://github.com/dice-discord/commando-provider-keyv/blob/master/src/KeyvProvider.js#L89))

**Comment by pizzafox** [comment]
Fixed in release [`v2.1.0`](https://www.npmjs.com/package/commando-provider-keyv/v/2.1.0)
